### PR TITLE
[contrib] Added vim-airline support (gui + cterm)

### PR DESCRIPTION
**Pull request by danilo-augusto**
screen shot 2017-02-09 at 02 42 50
screen shot 2017-02-09 at 02 42 44
screen shot 2017-02-09 at 02 42 32

### CODE REVIEW

**Comment by AlessandroYorba** [comment]
Dude that's simply awesome! Do you think you'd be willing to create a stand alone repo for it that? Or pull request here: https://github.com/vim-airline/vim-airline-themes

**Comment by danilo-augusto** [comment]
Thanks! I used only the colors from your original theme, which I find very well done. 

I can do a standalone repo if you like, but I think it creates a burden to Alduin users. After all it'd be two repos to look for, and one additional line cluttering the .vimrc. So I think it is better to integrate into the original Alduin repo like with the gruvbox colorscheme and many others, but it's your call.

However, I will indeed make a pull request to *vim-airline-themes* right away, it's a good idea. =)

**Comment by danilo-augusto** [comment]
Done. ;)
[vim-airline-themes pull request](https://github.com/vim-airline/vim-airline-themes/pull/69)

**Comment by AlessandroYorba** [comment]
@danilo-augusto yeah you're right! I'll merge this! love it!

**Comment by danilo-augusto** [comment]
Good! Do you plan to do it anytime soon?
Thnx!

**Comment by danilo-augusto** [comment]
As you can see [here](https://github.com/vim-airline/vim-airline-themes/pull/69), vim-airline-themes is going to merge now. I've squashed the commits here too, and cleaned the unnecessary modifications I've made before. This way you can merge as well, so the repo is self-contained, such as in [gruvbox](https://github.com/morhetz/gruvbox). ;)

**Comment by AlessandroYorba** [comment]
@danilo-augusto Awesome job! Thank You! I'll edit the Markdown with the new feature along with your credits! Thanks again

**Comment by danilo-augusto** [comment]
You are welcome. I just made a Sierra version too. Pull request is coming into [sierra](https://github.com/AlessandroYorba/Sierra) in a matter of minutes. :)

**Comment by danilo-augusto** [comment]
Your colorschemes are awesome! Very pleasant contrasts.

**Comment by AlessandroYorba** [comment]
@danilo-augusto so is your new theme! Congrats! btw, I added the credit link in my markdown, but now seeing how you have a theme would you like the link to land there? Thanks again

**Pull request merged**
